### ISSUE TITLE
Problems with nil queries

### ISSUE THREAD

**Issue by Chiro1975** [elifoster/urbandict-rb#1]
The API can't process a query that has invalid words. For example, "<>" or "." or "" provoke that the Urban Dictionary crashes. It has problems with all the queries that has no alphanumeric characters.

**Comment by elifoster** [comment]
This appears to be a problem with the Urban Dictionary API itself. Escaping the characters is not a solution because it changes the results (`%3C` on Urban Dictionary is different from `<`). I will add a half-solution of producing a clearer error so you can catch it in your code and alert the user of the problem.
